# Site settings
baseurl = "http://nosherosnationaux.com"
title = "Nos HÃ©ros Nationaux"
paginate = 5
buildFuture = true

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/glaiveVII/nosherosnationaux"

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "Baron Schwartz"
  twitter = "xaprb"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
